### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'dataPlaneURI')

### ISSUE THREAD

**Issue by bm77525-kr** [Azure/load-testing#69] opened 2023-11-08 00:26 UTC
**Describe the bug**

When running the github action in 2 out of 3 of our environments, the action fails with the error: `Cannot read properties of undefined (reading 'dataPlaneURI')`. This is failing here: https://github.com/Azure/load-testing/blob/main/src/main.ts#L315. I added some additional logging to output the response in the working environment vs the environment that produces the error.

## Working environment response

```json
{
  "id": "REDACTED",
  "name": "REDACTED",
  "type": "microsoft.loadtestservice/loadtests",
  "location": "eastus2",
  "tags": {},
  "systemData": {
    "createdBy": "REDACTED",
    "createdByType": "Application",
    "createdAt": "2023-07-12T15:59:44.4797918Z",
    "lastModifiedBy": "REDACTED",
    "lastModifiedByType": "Application",
    "lastModifiedAt": "2023-07-12T15:59:44.4797918Z"
  },
  "identity": {
    "principalId": "REDACTED",
    "tenantId": "REDACTED",
    "type": "SystemAssigned"
  },
  "properties": {
    "description": "",
    "dataPlaneURI": "REDACTED.eastus2.cnt-prod.loadtesting.azure.com",
    "encryption": null,
    "provisioningState": "Succeeded"
  }
}
```

## Response from environment that produces a failure

```json
{
  "value": [
    {
      "id": "REDACTED",
      "name": "REDACTED",
      "type": "microsoft.loadtestservice/loadtests",
      "location": "eastus2",
      "tags": {},
      "systemData": {
        "createdBy": "REDACTED",
        "createdByType": "Application",
        "createdAt": "2023-07-14T18:21:01.0686353Z",
        "lastModifiedBy": "REDACTED",
        "lastModifiedByType": "Application",
        "lastModifiedAt": "2023-07-14T18:21:01.0686353Z"
      },
      "identity": {
        "principalId": "REDACTED",
        "tenantId": "REDACTED",
        "type": "SystemAssigned"
      },
      "properties": {
        "description": "",
        "dataPlaneURI": "REDACTED.eastus2.cnt-prod.loadtesting.azure.com",
        "encryption": null,
        "provisioningState": "Succeeded"
      }
    }
  ]
}
```

**Expected behavior**

The action should account for both response formats.

**Comment by mohitpavan** [comment] 2023-11-22 07:09
@bm77525-kr, hi can you let us know more about the resource ? in my knowledge the get resource call should not return an array, it will return the dictionary ! can you try once more ? if the issue still persists, please let us know how old is the resource and the details about subscription.

**Comment by mohitpavan** [comment] 2023-11-22 08:47
can you help us with the config you have used also ?

**Comment by bm77525-kr** [comment] 2023-11-27 22:46
> @bm77525-kr, hi can you let us know more about the resource ? in my knowledge the get resource call should not return an array, it should return a single object ! can you try once more ? if the issue still persists, please let us know how old is the resource and the details about subscription.

@mohitpavan I believe the date the resource was created is in the response payload: `"createdAt": "2023-07-14T18:21:01.0686353Z",`. The one that works was created only a couple days earlier. Out of 3 instances in 3 different resource groups, only 1 is returning the expected format and all others are returning an array. And yes, we've tried many times and finally forked this action so we could output the response that's causing the failure which you see above. 

I'll be happy to provide subscription and resource specifics if there's a way to share those id's privately. I can say that the working instance is provisioned in an eastus2 instance provisioned in an eastus2 resource group. The other two are eastus2 instances provisioned in a centralus resource group. That would be the only differing thing from an infrastructure perspective.

**Comment by bm77525-kr** [comment] 2023-11-28 00:16
After some further investigation, I've narrowed this down (at least partially) to the case-sensitivity of the resource ID. I compared the resource ID in the portal to what the GH action is using and noticed the provider portion of the URL (`microsoft.loadtestservice`) is using lowercase in the action vs `Microsoft.LoadTestService` pull from the resource ID in the portal. The helper that generates the management plane URL uses lowercase for `microsoft.loadtestservice` part of the path: https://github.com/Azure/load-testing/blob/main/src/mappers.ts#L205.  In my fork I changed it to `Microsoft.LoadTestService` (uppercase as it is in the portal) and successfully ran the load test via the action in the resource groups where it previously failed. No array was returned in this case, just a single object as expected.

This still doesn't explain everything, like why it has always worked in one of our 3 environments/resource groups but not the others. Whatever the case, all lowercase `microsoft.loadtestservice` in 2 of our 3 environments seems to force an array to be returned as detailed in the original post and using uppercase doesn't.

**Comment by bm77525-kr** [comment] 2023-11-28 00:31
After further investigation, I've narrowed this down to a missing environment variable for the resource name that's injected into the GH action config. Because it was missing, it was an empty value being passed in which results in the generated ARM URL to be `https://management.azure.com/subscriptions/REDACTED/resourcegroups/REDACTED/providers/Microsoft.LoadTestService/loadtests/?api-version=2022-12-01` (notice no resource name after `loadtests/`) so the API appears to return an array of all load test resources in the resource group. I'm closing this out due to it being a configuration issue, but it might also be nice to also guard against these empty values a little better or improve the debugging experience.

**Comment by mohitpavan** [comment] 2023-12-06 07:50
@bm77525-kr  creating a workitem and will prioritise this one https://devdiv.visualstudio.com/OnlineServices/_workitems/edit/1921600/

thanks for the chance for us to look back on the validations, we will definetly take a look and work on the actionable errors.

**Comment by mohitpavan** [comment] 2023-12-06 08:22
reopening this by seeing the issue is on our side, we will close this when we updte our actions.

**Comment by mohitpavan** [comment] 2024-04-17 07:09
![image](https://github.com/Azure/load-testing/assets/112494281/4b666f7f-5607-482a-91bf-2f38ac17e9de)
we have added proper validation errors now.

**Closed by mohitpavan** 2024-04-17 07:09 UTC
Labels: need-to-triage
